Repository dlsu-lscs/arw-2025-web, pull requests merged in 2025-09, with the labels that each got.

#8 feat: search bar
  package-lock.json
  package.json
  src/components/search-bar.tsx
  src/components/ui/button.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/popover.tsx
  src/components/ui/sonner.tsx
Labels: enhancement

#2 feat: landing page
  package-lock.json
  package.json
  public/bg/st-lasalle-bg.webp
  public/logos/arw.webp
  public/logos/google.svg
  src/app/globals.css
  src/app/layout.tsx
  src/app/login/page.tsx
  src/components/login-btn.tsx
Labels: enhancement

#9 style: implemented org card, added tiny5 font
  public/dummy/interstellar-bg.jpg
  public/dummy/lscs-logo.svg
  src/app/globals.css
  src/features/orgs/components/org-card.tsx
Labels: enhancement

#20 feat: added dockerfile
  Dockerfile
Labels: enhancement

#31 Feat/cluster carousel logic
  next.config.ts
  src/app/globals.css
  src/components/ui/carousel.tsx
  src/features/clusters/containers/cluster-modal.tsx
  src/features/home/components/cluster-carousel.tsx
  src/features/home/container/home-page.tsx
  src/features/home/data/.gitkeep
  src/features/home/data/clusters.ts
Labels: enhancement

#35 feat: implement login
  package-lock.json
  package.json
  src/app/api/auth/refresh/route.ts
  src/app/auth/login/page.tsx
  src/app/auth/refresh/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/components/ui/avatar.tsx
  src/components/ui/dropdown-menu.tsx
  src/features/auth/containers/login-page.tsx
  src/features/auth/services/server-auth.ts
  src/features/auth/types/user.ts
  src/features/home/components/navbar.tsx
  src/features/home/container/home-page.tsx
  src/lib/axios.ts
Labels: enhancement

#37 Feat/36 fetch initial orgs using isr
  src/app/api/auth/refresh/route.ts
  src/app/page.tsx
  src/features/clusters/types/cluster.types.ts
  src/features/home/container/home-page.tsx
  src/features/orgs/components/org-card.tsx
  src/features/orgs/container/orgs-container.tsx
  src/features/orgs/services/clusters.services.ts
  src/features/orgs/services/orgs.services.ts
  src/features/orgs/types/colleges.types.ts
  src/features/orgs/types/orgs.types.ts
  src/features/orgs/types/pubs.types.ts
  src/lib/auth-cookies.ts
Labels: enhancement

#39 fix: hotfix logic when refresh is not found in db
  src/app/api/auth/refresh/route.ts
Labels: bug

#40 feat: uses color overlay for org card fallback
  src/features/orgs/components/org-card.tsx
  src/features/orgs/container/orgs-container.tsx
  src/lib/helpers.ts
Labels: enhancement

#42 Feat/15 tanstack fetch org csr for filtering orgs and search
  src/app/page.tsx
  src/features/home/container/home-page.tsx
  src/features/orgs/container/orgs-container.tsx
  src/features/orgs/queries/orgs.query.options.tsx
  src/features/orgs/services/client.orgs.services.ts
  src/features/orgs/types/orgs.types.ts
  src/lib/axios.ts
  src/lib/helpers.ts
Labels: enhancement

#45 Feat/indiv org view
  src/app/page.tsx
  src/components/collapsible-text.tsx
  src/components/modal/close-modal.tsx
  src/components/search-bar.tsx
  src/components/ui/carousel.tsx
  src/features/clusters/containers/cluster-modal.tsx
  src/features/clusters/store/useClusterModalStore.ts
  src/features/home/container/home-page.tsx
  src/features/orgs/components/org-card.tsx
  src/features/orgs/container/orgs-container.tsx
  src/features/orgs/container/orgs-modal.tsx
  src/features/orgs/hooks/use-prefetch-indiv-orgs.tsx
  src/features/orgs/queries/orgs.query.options.tsx
  src/features/orgs/store/useOrgsModalStore.ts
  src/lib/helpers.ts
Labels: enhancement

#63 feat: persist isSetVisible
  src/components/highlight-card.tsx
Labels: bug

#62 feat: fetched orgs randomly using seed
  package-lock.json
  package.json
  src/app/page.tsx
  src/features/home/container/home-page.tsx
  src/features/orgs/hooks/use-prefetch-org-clusters.tsx
  src/features/orgs/queries/orgs.query.options.tsx
  src/features/orgs/services/client.orgs.services.ts
  src/features/orgs/services/server.orgs.services.ts
Labels: enhancement

#89 Fix/org modal fix
  src/features/orgs/container/orgs-modal.tsx
Labels: documentation
